# Generated by Django 3.2.3 on 2021-05-31 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=50)),
                ('capital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=12, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=13, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_newspaper', models.BooleanField(default=False)),
                ('active_newspaper', models.BooleanField(default=True)),
                ('printed', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publisher.city')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperSection',
            fields=[
                ('name_section', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width_1', models.DecimalField(decimal_places=1, default=8, max_digits=3)),
                ('width_2', models.DecimalField(decimal_places=1, default=17, max_digits=3)),
                ('width_3', models.DecimalField(decimal_places=1, default=25, max_digits=3)),
                ('width_4', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_5', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_6', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_7', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_8', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_9', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('width_10', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('gutter', models.DecimalField(decimal_places=3, default=0.206, max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('font_size', models.DecimalField(decimal_places=1, default=7, max_digits=2)),
                ('font_leading', models.DecimalField(decimal_places=1, default=8, max_digits=3)),
                ('font_size_company', models.DecimalField(decimal_places=1, default=12, max_digits=3)),
                ('font_leading_company', models.DecimalField(decimal_places=1, default=13, max_digits=3)),
                ('tracking', models.CharField(choices=[('0', 'Normal'), ('-10', 'Low'), ('-20', 'Medium'), ('-30', 'High'), ('-40', 'Warning: Ultra')], default='Normal', max_length=50)),
                ('condensation', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('format_out', models.CharField(choices=[('.pdf', 'Pdf'), ('.docx', 'Docx'), ('.rtf', 'Rtf'), ('.doc', 'Doc 97/03'), ('.odt', 'Odt')], default='PDF', max_length=5)),
                ('price_cm', models.DecimalField(decimal_places=2, default=150, max_digits=7)),
                ('bold_italic', models.BooleanField(default=True)),
                ('edge', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('font_name', models.ForeignKey(default='Times New Roman', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='name_primary', to='publisher.font')),
                ('font_name_alternative', models.ForeignKey(default='Arial', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='name_secondary', to='publisher.font')),
                ('newspaper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationTypeName',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, max_length=1000, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_budget_delivery', models.PositiveIntegerField(default=2)),
                ('font_size', models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3, null=True)),
                ('font_leading', models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3, null=True)),
                ('font_size_company', models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3, null=True)),
                ('font_leading_company', models.DecimalField(blank=True, decimal_places=1, default=6, max_digits=3, null=True)),
                ('bold_italic', models.BooleanField(blank=True, default=True, null=True)),
                ('tracking', models.CharField(choices=[('0', 'Normal'), ('-10', 'Low'), ('-20', 'Medium'), ('-30', 'High'), ('-40', 'Warning: Ultra')], default='Normal', max_length=50)),
                ('condensation', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('special_format', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('0', 'Company name + Employer number + title + Flowing text'), ('1', 'Title or Employer number or Identity + Flowing text'), ('2', 'Flowing text'), ('3', 'Tagged'), ('4', 'Balance')], default='0', max_length=50)),
                ('font_name', models.ForeignKey(default='Times New Roman', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='name_special', to='publisher.font')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publicationtypename')),
                ('newspaper_section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.newspapersection')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('document_name', models.URLField(max_length=150)),
                ('days', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calculated_price_unity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.client')),
                ('publication_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publisher.publicationtype')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publisher.uf'),
        ),
    ]
