# Generated by Django 3.2.3 on 2021-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspapersection',
            name='bold_italic',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
