# Generated by Django 3.2.3 on 2021-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_alter_newspapersection_bold_italic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspapersection',
            old_name='bold_italic',
            new_name='bold',
        ),
        migrations.RemoveField(
            model_name='publicationtype',
            name='bold_italic',
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='italic',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='underline',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='bold',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='italic',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='underline',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
