# Generated by Django 3.2.3 on 2021-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20210606_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='deadline_days',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='deadline_hour',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='circulate_days',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='deadline_days',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='deadline_hour',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='price_cm_square',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='publicationtypename',
            name='quantity_days',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='newspapersection',
            name='price_cm',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=7, verbose_name='price_cm_column'),
        ),
    ]
