# Generated by Django 3.2.3 on 2021-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_auto_20210607_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='deadline_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newspapersection',
            name='deadline_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationtypename',
            name='quantity_days',
            field=models.IntegerField(null=True),
        ),
    ]
