# Generated by Django 3.2.3 on 2021-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_auto_20210607_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspapersection',
            name='maximum_height_budget',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='minimum_height',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='newspapersection',
            name='price_extra_color',
            field=models.DecimalField(blank=True, decimal_places=2, default=150, max_digits=7, null=True),
        ),
    ]
